os: linux

sudo: required

language: c

git:
  depth: false

branches: master

services:
  - docker

before_install:
  - docker pull thesofproject/sof && docker tag thesofproject/sof sof

script:
  - SOF_DESC=$(git describe --tag)
  - SOF_TAG=${SOF_DESC%-g*}
  - SOF_VER=${SOF_TAG#v}
  - SOF_REL=sof-imx-${SOF_VER}
  - export TRAVIS_TAG=${SOF_TAG}
  - install -d ./${SOF_REL}/{sof,sof-tplg}
  - ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -j imx8
  - ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -j imx8x
  - ./scripts/docker-run.sh ./scripts/build-tools.sh
  - cp -v ./LICENCE ./${SOF_REL}/sof/
  - cp -v ./build_imx*_gcc/sof-imx* ./${SOF_REL}/sof/
  - cp -v ./tools/build_tools/topology/sof-imx* ./${SOF_REL}/sof-tplg/
  - tar czvf ${SOF_REL}.tar.gz ${SOF_REL}

deploy:
  provider: releases
  token: ${GITHUB_TOKEN}
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
  file: ${SOF_REL}.tar.gz
  name: ${SOF_REL}
